from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HostContract:
    project_user: str
    dac_card: str
    dac_device: int
    loopback_index: int
    loopback_id: str
    sample_rate: int = 44100
    sample_format: str = "S16_LE"
    period_size: int = 1024
    buffer_size: int = 8192
    chunksize: int = 1024
    target_level: int = 2048
    limiter_db: float = -1.0
    camilladsp_version: str = "4.1.3"
    camilladsp_sha256: str = "e04c7a6603e9482bab33c1e18afc41d3c07410b54ba9c246eda69f7e9cbaedfa"
    pre_stage_c_alsa_sha256: str = "08d000933e132af4fe0d66f1f80fd6ba08d15398b98f5ea986f69709139e74b9"


def module_load() -> str:
    return "# Managed candidate generated by A Clockwork Plex Stage C1.\nsnd_aloop\n"


def module_options(c: HostContract) -> str:
    return (
        "# Managed candidate generated by A Clockwork Plex Stage C1.\n"
        f"options snd_aloop index={c.loopback_index} id={c.loopback_id} "
        "pcm_substreams=2 pcm_notify=1\n"
    )


def defaults(c: HostContract) -> str:
    return f"""# Managed candidate generated by A Clockwork Plex Stage C1.
PROJECT_USER={c.project_user}
DAC_CARD={c.dac_card}
DAC_DEVICE={c.dac_device}
LOOPBACK_INDEX={c.loopback_index}
LOOPBACK_ID={c.loopback_id}
SAMPLE_RATE={c.sample_rate}
FORMAT={c.sample_format}
PERIOD_SIZE={c.period_size}
BUFFER_SIZE={c.buffer_size}
CAMILLADSP_VERSION={c.camilladsp_version}
CAMILLADSP_SHA256={c.camilladsp_sha256}
PRE_STAGE_C_ALSA_SHA256={c.pre_stage_c_alsa_sha256}
ACTIVE_ALSA_CONFIG=/etc/alsa/conf.d/99-a-clockwork-plex-shared.conf
SPLIT_ROUTE=/etc/a-clockwork-plex/audio-routes/split-bus.conf
DIRECT_FAILBACK_ROUTE=/etc/a-clockwork-plex/audio-routes/direct-alarm-bypass.conf
CAMILLADSP_BINARY=/usr/local/lib/a-clockwork-plex/camilladsp-{c.camilladsp_version}/camilladsp
CAMILLADSP_CONFIG=/etc/a-clockwork-plex/camilladsp-split-bus.yml
STATE_DIR=/var/lib/a-clockwork-plex/split-bus
"""


def split_route(c: HostContract) -> str:
    return f"""# A Clockwork Plex Stage C split-bus candidate.
# Music occupies loopback channels 0/1; alarm occupies 2/3.
pcm.acp_dmix {{
    type dmix
    ipc_key 1094934536
    ipc_key_add_uid false
    ipc_perm 0666
    slave {{
        pcm \"hw:{c.loopback_index},0,0\"
        format {c.sample_format}
        rate {c.sample_rate}
        channels 4
        period_size {c.period_size}
        buffer_size {c.buffer_size}
    }}
    bindings {{ 0 0 1 1 2 2 3 3 }}
}}
pcm.acp_music_route {{
    type route
    slave {{ pcm \"acp_dmix\" channels 4 }}
    ttable {{ 0.0 1 1.1 1 }}
}}
pcm.acp_alarm_route {{
    type route
    slave {{ pcm \"acp_dmix\" channels 4 }}
    ttable {{ 0.2 1 1.3 1 }}
}}
pcm.acp_master_volume {{
    type softvol
    slave.pcm \"acp_music_route\"
    control {{ name \"A Clockwork Master\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_master {{ type plug slave.pcm \"acp_master_volume\" hint {{ show on description \"A Clockwork Plex - Music master\" }} }}
pcm.acp_plexamp_volume {{
    type softvol
    slave.pcm \"acp_master\"
    control {{ name \"A Clockwork Plexamp\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_plexamp {{ type plug slave.pcm \"acp_plexamp_volume\" hint {{ show on description \"A Clockwork Plex - Plexamp\" }} }}
pcm.acp_airplay_volume {{
    type softvol
    slave.pcm \"acp_master\"
    control {{ name \"A Clockwork AirPlay\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_airplay {{ type plug slave.pcm \"acp_airplay_volume\" hint {{ show on description \"A Clockwork Plex - AirPlay\" }} }}
pcm.acp_alarm_volume {{
    type softvol
    slave.pcm \"acp_alarm_route\"
    control {{ name \"A Clockwork Alarm\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_alarm {{ type plug slave.pcm \"acp_alarm_volume\" hint {{ show on description \"A Clockwork Plex - Independent alarm ceiling\" }} }}
"""


def direct_route(c: HostContract) -> str:
    return f"""# A Clockwork Plex Stage C direct alarm-bypass failback candidate.
pcm.acp_dmix {{
    type dmix
    ipc_key 1094931536
    ipc_key_add_uid false
    ipc_perm 0666
    slave {{
        pcm \"hw:CARD={c.dac_card},DEV={c.dac_device}\"
        format {c.sample_format}
        rate {c.sample_rate}
        channels 2
        period_size {c.period_size}
        buffer_size {c.buffer_size}
    }}
    bindings {{ 0 0 1 1 }}
}}
pcm.acp_master_volume {{
    type softvol
    slave.pcm \"acp_dmix\"
    control {{ name \"A Clockwork Master\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_master {{ type plug slave.pcm \"acp_master_volume\" hint {{ show on description \"A Clockwork Plex - Music master direct failback\" }} }}
pcm.acp_plexamp_volume {{
    type softvol
    slave.pcm \"acp_master\"
    control {{ name \"A Clockwork Plexamp\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_plexamp {{ type plug slave.pcm \"acp_plexamp_volume\" hint {{ show on description \"A Clockwork Plex - Plexamp\" }} }}
pcm.acp_airplay_volume {{
    type softvol
    slave.pcm \"acp_master\"
    control {{ name \"A Clockwork AirPlay\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_airplay {{ type plug slave.pcm \"acp_airplay_volume\" hint {{ show on description \"A Clockwork Plex - AirPlay\" }} }}
pcm.acp_alarm_volume {{
    type softvol
    slave.pcm \"acp_dmix\"
    control {{ name \"A Clockwork Alarm\" card \"{c.dac_card}\" }}
    min_dB -51.0
    max_dB 0.0
    resolution 256
}}
pcm.acp_alarm {{ type plug slave.pcm \"acp_alarm_volume\" hint {{ show on description \"A Clockwork Plex - Independent alarm direct failback\" }} }}
"""


def camilladsp_config(c: HostContract) -> str:
    return f"""---
title: \"A Clockwork Plex Stage C split bus\"
description: \"Music-only EQ and headroom, independent alarm, final limiter\"
devices:
  samplerate: {c.sample_rate}
  chunksize: {c.chunksize}
  queuelimit: 4
  silence_timeout: 0
  target_level: {c.target_level}
  adjust_period: 1
  enable_rate_adjust: true
  resampler: null
  volume_ramp_time: 100
  volume_limit: 0.0
  capture:
    type: Alsa
    channels: 4
    device: \"hw:{c.loopback_index},1,0\"
    format: {c.sample_format}
  playback:
    type: Alsa
    channels: 2
    device: \"hw:CARD={c.dac_card},DEV={c.dac_device}\"
    format: {c.sample_format}
filters:
  bass: {{type: Biquad, parameters: {{type: Lowshelf, freq: 125, gain: 0.0, slope: 6}}}}
  mid: {{type: Biquad, parameters: {{type: Peaking, freq: 1000, gain: 0.0, q: 0.7}}}}
  treble: {{type: Biquad, parameters: {{type: Highshelf, freq: 4000, gain: 0.0, slope: 6}}}}
  headroom: {{type: Gain, parameters: {{gain: 0.0, scale: dB, inverted: false, mute: false}}}}
  final_safety_limiter: {{type: Limiter, parameters: {{soft_clip: false, clip_limit: {c.limiter_db}}}}}
mixers:
  combine_music_and_alarm:
    channels: {{in: 4, out: 2}}
    mapping:
      - dest: 0
        sources:
          - {{channel: 0, gain: 0, scale: dB, inverted: false}}
          - {{channel: 2, gain: 0, scale: dB, inverted: false}}
      - dest: 1
        sources:
          - {{channel: 1, gain: 0, scale: dB, inverted: false}}
          - {{channel: 3, gain: 0, scale: dB, inverted: false}}
pipeline:
  - {{type: Filter, channels: [0, 1], names: [bass, mid, treble, headroom]}}
  - {{type: Mixer, name: combine_music_and_alarm}}
  - {{type: Filter, channels: [0, 1], names: [final_safety_limiter]}}
"""
